package toko.kelontong;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hakim frh
 */
public class Panel_Stok extends javax.swing.JPanel {

    /**
     * Creates new form Page_tambahBarang
     */
    
    
    String editkode;
    String[] stokkode={};
    int editpengeluaran,editsubtotal;
    
    Date date = new Date();
    SimpleDateFormat m = new SimpleDateFormat("yyyy-MM-dd");    
    DefaultTableModel modelstok = new DefaultTableModel();
   public Panel_Stok() {
        initComponents();
        
        pn_buton.setVisible(true);
        pn_listBarang.setVisible(true);
        pn_tambahStok.setVisible(false);
        pn_tambahBarang.setVisible(false);
        pn_editBarang.setVisible(false);
        load_table();
        load_CmbBox();
        tabel_stok();
        btn_pn_listBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/list on.png")));
        btn_pn_tambahBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah barang off.png")));
        btn_pn_tambahStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah stok off.png")));
    }
    public static String[] addX(int n, String arr[], String x){
       int i;
       String newarr[] = new String[n + 1];
       for (i = 0; i < n; i++)
           newarr[i] = arr[i];
   
       newarr[n] = x;
       return newarr;
   }
    
    
    private void load_CmbBox(){
        try{
            String sql = "SELECT * FROM stok_barang order by nama_barang asc;";
            java.sql.Connection conn= (Connection) koneksi.configDB();
            java.sql.PreparedStatement stm=conn.prepareStatement(sql);
            java.sql.ResultSet res = stm.executeQuery(sql);
            int item = box_editkode.getItemCount();
            for(int i = 0; i < item; i++){
                box_editkode.removeItemAt(0);
            }
            while(res.next()){
                box_editkode.addItem(res.getString("kode_barang") +" - " +res.getString("nama_barang"));
            }
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
        
    } 
    
    public void tabel_stok(){
        modelstok.addColumn("Nama Barang");
        modelstok.addColumn("Harga");
        modelstok.addColumn("Jumlah");
        modelstok.addColumn("Subtotal");
        
        
        jTable2.setModel(modelstok);
    }
    public void clear_edit(){
        load_table();
        pn_listBarang.setVisible(true);
        pn_tambahBarang.setVisible(false);
        pn_tambahStok.setVisible(false);
        pn_editBarang.setVisible(false);
        editkode="";
            txt_editnama.setText("");
            txt_editjual.setText("");
            txt_editbeli.setText("");
            txt_editkode.setText("");
    }
    
    
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Stok Barang");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        
        try{
            
            String sql = "SELECT * FROM stok_barang";
            java.sql.Connection conn= (Connection) koneksi.configDB();
            java.sql.PreparedStatement stm=conn.prepareStatement(sql);
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()){
                model.addRow(new Object[]{
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                });
            }
            jTable1.setModel(model);
        }catch (Exception e){
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_listBarang = new javax.swing.JPanel();
        lb_list_Barang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pn_editBarang = new javax.swing.JPanel();
        lb_editBarang = new javax.swing.JLabel();
        txt_editnama = new javax.swing.JTextField();
        lbl_editbarang = new javax.swing.JLabel();
        txt_editbeli = new javax.swing.JTextField();
        lb_harga_Beli1 = new javax.swing.JLabel();
        txt_editjual = new javax.swing.JTextField();
        lb_harga_Jual1 = new javax.swing.JLabel();
        txt_editkode = new javax.swing.JTextField();
        lb_kode_Barang1 = new javax.swing.JLabel();
        btn_edit_kembali = new javax.swing.JLabel();
        btn_edit_simpan = new javax.swing.JLabel();
        pn_tambahBarang = new javax.swing.JPanel();
        lb_Tambah_Barang = new javax.swing.JLabel();
        txt_tambahnama = new javax.swing.JTextField();
        lb_Nama_barang = new javax.swing.JLabel();
        txt_tambahbeli = new javax.swing.JTextField();
        lb_harga_Beli = new javax.swing.JLabel();
        txt_tambahjual = new javax.swing.JTextField();
        lb_harga_Jual = new javax.swing.JLabel();
        txt_tambahsatuanstok = new javax.swing.JTextField();
        lb_satuan_Stok = new javax.swing.JLabel();
        txt_tambahkode = new javax.swing.JTextField();
        lb_kode_Barang = new javax.swing.JLabel();
        btn_tambah_simpan = new javax.swing.JLabel();
        pn_tambahStok = new javax.swing.JPanel();
        btn_tambah_stok = new javax.swing.JButton();
        txt_stokjumlah = new javax.swing.JTextField();
        kode_Barang1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kode_Barang2 = new javax.swing.JLabel();
        txt_stokharga = new javax.swing.JTextField();
        harga_Beli1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lbl_editpengeluaran = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_tambah_daftar = new javax.swing.JButton();
        box_editkode = new javax.swing.JComboBox<>();
        pn_buton = new javax.swing.JPanel();
        btn_pn_listBarang = new javax.swing.JLabel();
        btn_pn_tambahStok = new javax.swing.JLabel();
        btn_pn_tambahBarang = new javax.swing.JLabel();
        BG_button = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(768, 503));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_listBarang.setBackground(new java.awt.Color(255, 255, 255));
        pn_listBarang.setLayout(null);

        lb_list_Barang.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        lb_list_Barang.setText("List Barang");
        pn_listBarang.add(lb_list_Barang);
        lb_list_Barang.setBounds(30, 10, 250, 40);

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Sisa Stok", "Harga Beli", "Harga Jual"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setName(""); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pn_listBarang.add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 670, 340);

        add(pn_listBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 710, 450));

        pn_editBarang.setBackground(new java.awt.Color(255, 255, 255));
        pn_editBarang.setLayout(null);

        lb_editBarang.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        lb_editBarang.setText("Edit Barang");
        pn_editBarang.add(lb_editBarang);
        lb_editBarang.setBounds(30, 10, 250, 40);

        txt_editnama.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_editnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_editnamaKeyReleased(evt);
            }
        });
        pn_editBarang.add(txt_editnama);
        txt_editnama.setBounds(70, 90, 330, 30);

        lbl_editbarang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_editbarang.setText("Nama Barang");
        pn_editBarang.add(lbl_editbarang);
        lbl_editbarang.setBounds(70, 70, 140, 20);

        txt_editbeli.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pn_editBarang.add(txt_editbeli);
        txt_editbeli.setBounds(70, 160, 330, 30);

        lb_harga_Beli1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_harga_Beli1.setText("Harga Jual");
        pn_editBarang.add(lb_harga_Beli1);
        lb_harga_Beli1.setBounds(70, 200, 140, 30);

        txt_editjual.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pn_editBarang.add(txt_editjual);
        txt_editjual.setBounds(70, 230, 330, 30);

        lb_harga_Jual1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_harga_Jual1.setText("Harga Beli");
        pn_editBarang.add(lb_harga_Jual1);
        lb_harga_Jual1.setBounds(70, 140, 140, 20);

        txt_editkode.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_editkode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_editkodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_editkodeKeyTyped(evt);
            }
        });
        pn_editBarang.add(txt_editkode);
        txt_editkode.setBounds(70, 300, 330, 30);

        lb_kode_Barang1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_kode_Barang1.setText("Kode Barang");
        pn_editBarang.add(lb_kode_Barang1);
        lb_kode_Barang1.setBounds(70, 280, 140, 20);

        btn_edit_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/kembali.png"))); // NOI18N
        btn_edit_kembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit_kembaliMouseClicked(evt);
            }
        });
        pn_editBarang.add(btn_edit_kembali);
        btn_edit_kembali.setBounds(70, 350, 180, 60);

        btn_edit_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/edit.png"))); // NOI18N
        btn_edit_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit_simpanMouseClicked(evt);
            }
        });
        pn_editBarang.add(btn_edit_simpan);
        btn_edit_simpan.setBounds(530, 350, 180, 60);

        add(pn_editBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 720, 450));

        pn_tambahBarang.setBackground(new java.awt.Color(255, 255, 255));
        pn_tambahBarang.setLayout(null);

        lb_Tambah_Barang.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        lb_Tambah_Barang.setText("Tambah Barang");
        pn_tambahBarang.add(lb_Tambah_Barang);
        lb_Tambah_Barang.setBounds(30, 10, 250, 40);

        txt_tambahnama.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_tambahnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tambahnamaActionPerformed(evt);
            }
        });
        txt_tambahnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tambahnamaKeyReleased(evt);
            }
        });
        pn_tambahBarang.add(txt_tambahnama);
        txt_tambahnama.setBounds(70, 90, 330, 30);

        lb_Nama_barang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_Nama_barang.setText("Nama Barang");
        pn_tambahBarang.add(lb_Nama_barang);
        lb_Nama_barang.setBounds(70, 70, 140, 20);

        txt_tambahbeli.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pn_tambahBarang.add(txt_tambahbeli);
        txt_tambahbeli.setBounds(70, 160, 330, 30);

        lb_harga_Beli.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_harga_Beli.setText("Harga Beli");
        pn_tambahBarang.add(lb_harga_Beli);
        lb_harga_Beli.setBounds(70, 140, 140, 20);

        txt_tambahjual.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pn_tambahBarang.add(txt_tambahjual);
        txt_tambahjual.setBounds(70, 230, 330, 30);

        lb_harga_Jual.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_harga_Jual.setText("Harga Jual");
        pn_tambahBarang.add(lb_harga_Jual);
        lb_harga_Jual.setBounds(70, 210, 140, 20);

        txt_tambahsatuanstok.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_tambahsatuanstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tambahsatuanstokKeyReleased(evt);
            }
        });
        pn_tambahBarang.add(txt_tambahsatuanstok);
        txt_tambahsatuanstok.setBounds(70, 300, 330, 30);

        lb_satuan_Stok.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_satuan_Stok.setText("Satuan Stok @");
        pn_tambahBarang.add(lb_satuan_Stok);
        lb_satuan_Stok.setBounds(70, 280, 140, 20);

        txt_tambahkode.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_tambahkode.setName(""); // NOI18N
        txt_tambahkode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tambahkodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tambahkodeKeyTyped(evt);
            }
        });
        pn_tambahBarang.add(txt_tambahkode);
        txt_tambahkode.setBounds(70, 370, 330, 30);

        lb_kode_Barang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lb_kode_Barang.setText("Kode Barang");
        pn_tambahBarang.add(lb_kode_Barang);
        lb_kode_Barang.setBounds(70, 350, 140, 20);

        btn_tambah_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/simpan.png"))); // NOI18N
        btn_tambah_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambah_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambah_simpanMouseClicked(evt);
            }
        });
        pn_tambahBarang.add(btn_tambah_simpan);
        btn_tambah_simpan.setBounds(460, 340, 220, 60);

        add(pn_tambahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 710, 450));

        pn_tambahStok.setBackground(new java.awt.Color(255, 255, 255));
        pn_tambahStok.setLayout(null);

        btn_tambah_stok.setBackground(new java.awt.Color(255, 255, 255));
        btn_tambah_stok.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btn_tambah_stok.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah_stok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/Tambah Stok.png"))); // NOI18N
        btn_tambah_stok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambah_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_stokActionPerformed(evt);
            }
        });
        pn_tambahStok.add(btn_tambah_stok);
        btn_tambah_stok.setBounds(400, 310, 240, 80);

        txt_stokjumlah.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pn_tambahStok.add(txt_stokjumlah);
        txt_stokjumlah.setBounds(70, 260, 240, 30);

        kode_Barang1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        kode_Barang1.setText("Jumlah Stok");
        pn_tambahStok.add(kode_Barang1);
        kode_Barang1.setBounds(70, 240, 140, 20);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("Total Pengeluaran");
        pn_tambahStok.add(jLabel8);
        jLabel8.setBounds(400, 230, 250, 30);

        kode_Barang2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        kode_Barang2.setText("Kode Barang");
        pn_tambahStok.add(kode_Barang2);
        kode_Barang2.setBounds(70, 100, 140, 20);

        txt_stokharga.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pn_tambahStok.add(txt_stokharga);
        txt_stokharga.setBounds(70, 190, 240, 30);

        harga_Beli1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        harga_Beli1.setText("Harga Beli");
        pn_tambahStok.add(harga_Beli1);
        harga_Beli1.setBounds(70, 170, 140, 20);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Barang", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        pn_tambahStok.add(jScrollPane2);
        jScrollPane2.setBounds(370, 120, 320, 100);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        jLabel9.setText("Tambah Stok");
        pn_tambahStok.add(jLabel9);
        jLabel9.setBounds(30, 10, 250, 40);

        lbl_editpengeluaran.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_editpengeluaran.setText("0");
        pn_tambahStok.add(lbl_editpengeluaran);
        lbl_editpengeluaran.setBounds(440, 260, 160, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Rp.");
        pn_tambahStok.add(jLabel2);
        jLabel2.setBounds(410, 260, 30, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/orange.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        pn_tambahStok.add(jLabel3);
        jLabel3.setBounds(400, 260, 240, 30);

        btn_tambah_daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah ke daftar.png"))); // NOI18N
        btn_tambah_daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambah_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_daftarActionPerformed(evt);
            }
        });
        pn_tambahStok.add(btn_tambah_daftar);
        btn_tambah_daftar.setBounds(70, 310, 200, 40);

        box_editkode.setMaximumRowCount(1000);
        box_editkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_editkodeActionPerformed(evt);
            }
        });
        pn_tambahStok.add(box_editkode);
        box_editkode.setBounds(70, 120, 240, 30);

        add(pn_tambahStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 710, 450));

        pn_buton.setBackground(new java.awt.Color(255, 255, 255));
        pn_buton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pn_listBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/list on.png"))); // NOI18N
        btn_pn_listBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pn_listBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pn_listBarangMouseClicked(evt);
            }
        });
        pn_buton.add(btn_pn_listBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        btn_pn_tambahStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah stok off.png"))); // NOI18N
        btn_pn_tambahStok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pn_tambahStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pn_tambahStokMouseClicked(evt);
            }
        });
        pn_buton.add(btn_pn_tambahStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        btn_pn_tambahBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah barang off.png"))); // NOI18N
        btn_pn_tambahBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pn_tambahBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pn_tambahBarangMouseClicked(evt);
            }
        });
        pn_buton.add(btn_pn_tambahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        BG_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg submenu.png"))); // NOI18N
        BG_button.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BG_button.setIconTextGap(0);
        pn_buton.add(BG_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        add(pn_buton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambah_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_stokActionPerformed
        // TODO add your handling code here:
        int baris=jTable2.getRowCount();
        boolean status=true;
        for(int i=0; i<=baris-1; i++){
            try{
                 String sql = "UPDATE stok_barang SET"
                    +" `harga_beli`= '" +jTable2.getValueAt(i,1).toString() +"',"
                    +" `sisa_stok`= sisa_stok+" +jTable2.getValueAt(i,2).toString()
                    +" WHERE `kode_barang`='"+stokkode[i].toString()+"';";
                 System.out.println(sql);
                java.sql.Connection conn= (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                
                load_table();
            }catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
                status=false;
            }    
        }
        
            try{
            String sql = "INSERT INTO `pengeluaran`(`tanggal`, `modal`) VALUES ('"
            +m.format(date) +"','"
            +editpengeluaran +"')";
            java.sql.Connection conn= (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            
            
            
            modelstok.setRowCount(0);
            jTable2.setModel(modelstok);
            txt_stokharga.setText("");
            txt_stokjumlah.setText("");
            //txt_stokkode.setText("");
            
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            status = false;
        }
            if(status){
            JOptionPane.showMessageDialog(null, "Stok Berhasil Ditambahkan");
        }
        
        
    }//GEN-LAST:event_btn_tambah_stokActionPerformed

    private void btn_tambah_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_daftarActionPerformed
        // TODO add your handling code here:
        
        try{
            String kode = box_editkode.getSelectedItem().toString();
            kode=kode.substring(0,kode.indexOf("-"));
            String sql = "SELECT * FROM stok_barang WHERE kode_barang ='" +kode +"';";
            java.sql.Connection conn= (Connection) koneksi.configDB();
            java.sql.PreparedStatement stm=conn.prepareStatement(sql);
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            if(res.next()){
            editsubtotal=Integer.parseInt(txt_stokharga.getText())*Integer.parseInt(txt_stokjumlah.getText());
            
            stokkode=addX(stokkode.length,stokkode,kode);
            modelstok.addRow(new Object[]{
                res.getString(2),
                txt_stokharga.getText(),
                txt_stokjumlah.getText(),
                Integer.toString(editsubtotal)
            });
            jTable2.setModel(modelstok);
            
            int baris=jTable2.getRowCount();
                System.out.println(baris);
                //baris++;
            editpengeluaran=0;
            for(int i=0; i<=baris-1; i++){
                editpengeluaran+=Integer.parseInt(jTable2.getValueAt(i,3).toString());
                System.out.println(editpengeluaran);
            }
            System.out.println("keluar : " +editpengeluaran);
            lbl_editpengeluaran.setText(Integer.toString(editpengeluaran));
            
           }
        }catch (Exception e){
            //System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btn_tambah_daftarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        editkode = jTable1.getValueAt(baris, 0).toString();
        txt_editkode.setText(editkode);
        
        if(jTable1.getValueAt(baris, 1)== null){
            txt_editnama.setText("");
        }else{
            txt_editnama.setText(jTable1.getValueAt(baris,1).toString());
        }
        if(jTable1.getValueAt(baris, 3)== null){
            txt_editbeli.setText("");
        }else{
            txt_editbeli.setText(jTable1.getValueAt(baris,3).toString());
        }
        if(jTable1.getValueAt(baris, 4)== null){
            txt_editjual.setText("");
        }else{
            txt_editjual.setText(jTable1.getValueAt(baris,4).toString());
        }
        pn_listBarang.setVisible(false);
        pn_tambahBarang.setVisible(false);
        pn_tambahStok.setVisible(false);
        pn_editBarang.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_pn_listBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pn_listBarangMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        pn_listBarang.setVisible(true);
        pn_tambahBarang.setVisible(false);
        pn_tambahStok.setVisible(false);
        pn_editBarang.setVisible(false);
        btn_pn_listBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/list on.png")));
        btn_pn_tambahBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah barang off.png")));
        btn_pn_tambahStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah stok off.png")));
        load_table();
    }//GEN-LAST:event_btn_pn_listBarangMouseClicked

    private void btn_pn_tambahBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pn_tambahBarangMouseClicked
        // TODO add your handling code here:
        pn_listBarang.setVisible(false);
        pn_tambahBarang.setVisible(true);
        pn_tambahStok.setVisible(false);
        pn_editBarang.setVisible(false);
        btn_pn_listBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/list off.png")));
        btn_pn_tambahBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah barang on.png")));
        btn_pn_tambahStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah stok off.png")));
    }//GEN-LAST:event_btn_pn_tambahBarangMouseClicked

    private void btn_pn_tambahStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pn_tambahStokMouseClicked
        // TODO add your handling code here:
        pn_listBarang.setVisible(false);
        pn_tambahBarang.setVisible(false);
        pn_tambahStok.setVisible(true);
        pn_editBarang.setVisible(false);
        btn_pn_listBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/list off.png")));
        btn_pn_tambahBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah barang off.png")));
        btn_pn_tambahStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok/tambah stok on.png")));
        load_CmbBox();
    }//GEN-LAST:event_btn_pn_tambahStokMouseClicked

    private void btn_edit_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_simpanMouseClicked
        // TODO add your handling code here:
         try{
            String sql = "UPDATE stok_barang"
                    +" SET nama_barang ='" +txt_editnama.getText()
                    +"', harga_jual='" +txt_editjual.getText()
                    +"', kode_barang='" +txt_editkode.getText()
                    +"', harga_beli='" +txt_editbeli.getText() 
                    +"' WHERE kode_barang ='" +editkode +"'";
            java.sql.Connection conn= (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil diedit");
            clear_edit();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_edit_simpanMouseClicked

    private void btn_edit_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_kembaliMouseClicked
        // TODO add your handling code here:
        clear_edit();
    }//GEN-LAST:event_btn_edit_kembaliMouseClicked

    private void btn_tambah_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambah_simpanMouseClicked
        // TODO add your handling code here:
         try{
            String sql = "INSERT INTO `stok_barang`(`kode_barang`, `nama_barang`, `satuan_stok`, `harga_beli`, `harga_jual`) VALUES ('"
            +txt_tambahkode.getText() +"','"
            +txt_tambahnama.getText() +"','"
            +txt_tambahsatuanstok.getText() +"','"
            +txt_tambahbeli.getText() +"','"
            +txt_tambahjual.getText() +"')";
            java.sql.Connection conn= (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Barang Ditambahkan");
            load_table();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_tambah_simpanMouseClicked

    private void box_editkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_editkodeActionPerformed
        // TODO add your handling code here:
        try{
            String kode = box_editkode.getSelectedItem().toString();
            kode=kode.substring(0,kode.indexOf("-"));
            String sql = "SELECT * FROM stok_barang WHERE kode_barang ='" +kode +"';";
            java.sql.Connection conn= (Connection) koneksi.configDB();
            java.sql.PreparedStatement stm=conn.prepareStatement(sql);
            java.sql.ResultSet res = stm.executeQuery(sql);
            if(res.next()){
            txt_stokharga.setText(res.getString("harga_beli"));
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_box_editkodeActionPerformed

    private void txt_tambahnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tambahnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tambahnamaActionPerformed

    private void txt_tambahnamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tambahnamaKeyReleased
        // TODO add your handling code here:
        txt_tambahnama.setText(txt_tambahnama.getText().toUpperCase());
    }//GEN-LAST:event_txt_tambahnamaKeyReleased

    private void txt_tambahkodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tambahkodeKeyReleased
        // TODO add your handling code here:
        txt_tambahkode.setText(txt_tambahkode.getText().toUpperCase());
    }//GEN-LAST:event_txt_tambahkodeKeyReleased

    private void txt_editnamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_editnamaKeyReleased
        // TODO add your handling code here:
        txt_editnama.setText(txt_editnama.getText().toUpperCase());
    }//GEN-LAST:event_txt_editnamaKeyReleased

    private void txt_editkodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_editkodeKeyReleased
        // TODO add your handling code here:
        txt_editkode.setText(txt_editkode.getText().toUpperCase());
    }//GEN-LAST:event_txt_editkodeKeyReleased

    private void txt_tambahsatuanstokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tambahsatuanstokKeyReleased
        // TODO add your handling code here:
        txt_tambahsatuanstok.setText(txt_tambahsatuanstok.getText().toUpperCase());
    }//GEN-LAST:event_txt_tambahsatuanstokKeyReleased

    private void txt_editkodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_editkodeKeyTyped
        // TODO add your handling code here:
        if (txt_editkode.getText().length()>=5){
            JOptionPane.showMessageDialog(null,"Panjang Huruf Maksimal 5");
            evt.consume();
        }
    }//GEN-LAST:event_txt_editkodeKeyTyped

    private void txt_tambahkodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tambahkodeKeyTyped
        // TODO add your handling code here:
        if (txt_tambahkode.getText().length()>=5){
            JOptionPane.showMessageDialog(null,"Panjang Huruf Maksimal 5");
            evt.consume();
        }
    }//GEN-LAST:event_txt_tambahkodeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_button;
    private javax.swing.JComboBox<String> box_editkode;
    private javax.swing.JLabel btn_edit_kembali;
    private javax.swing.JLabel btn_edit_simpan;
    private javax.swing.JLabel btn_pn_listBarang;
    private javax.swing.JLabel btn_pn_tambahBarang;
    private javax.swing.JLabel btn_pn_tambahStok;
    private javax.swing.JButton btn_tambah_daftar;
    private javax.swing.JLabel btn_tambah_simpan;
    private javax.swing.JButton btn_tambah_stok;
    private javax.swing.JLabel harga_Beli1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel kode_Barang1;
    private javax.swing.JLabel kode_Barang2;
    private javax.swing.JLabel lb_Nama_barang;
    private javax.swing.JLabel lb_Tambah_Barang;
    private javax.swing.JLabel lb_editBarang;
    private javax.swing.JLabel lb_harga_Beli;
    private javax.swing.JLabel lb_harga_Beli1;
    private javax.swing.JLabel lb_harga_Jual;
    private javax.swing.JLabel lb_harga_Jual1;
    private javax.swing.JLabel lb_kode_Barang;
    private javax.swing.JLabel lb_kode_Barang1;
    private javax.swing.JLabel lb_list_Barang;
    private javax.swing.JLabel lb_satuan_Stok;
    private javax.swing.JLabel lbl_editbarang;
    private javax.swing.JLabel lbl_editpengeluaran;
    private javax.swing.JPanel pn_buton;
    private javax.swing.JPanel pn_editBarang;
    private javax.swing.JPanel pn_listBarang;
    private javax.swing.JPanel pn_tambahBarang;
    private javax.swing.JPanel pn_tambahStok;
    private javax.swing.JTextField txt_editbeli;
    private javax.swing.JTextField txt_editjual;
    private javax.swing.JTextField txt_editkode;
    private javax.swing.JTextField txt_editnama;
    private javax.swing.JTextField txt_stokharga;
    private javax.swing.JTextField txt_stokjumlah;
    private javax.swing.JTextField txt_tambahbeli;
    private javax.swing.JTextField txt_tambahjual;
    private javax.swing.JTextField txt_tambahkode;
    private javax.swing.JTextField txt_tambahnama;
    private javax.swing.JTextField txt_tambahsatuanstok;
    // End of variables declaration//GEN-END:variables
}
