package toko.kelontong;

import java.awt.Cursor;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nama_pemilik = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_nama_toko = new javax.swing.JTextField();
        btn_selanjutnya = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_emailconfirm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/judul_1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 890, 70));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 146, 210));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 890, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nama_txtfield.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txt_nama_pemilik.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 146, 210)));
        txt_nama_pemilik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nama_pemilikKeyReleased(evt);
            }
        });
        jPanel1.add(txt_nama_pemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 142, 246, 30));

        txt_alamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 146, 210)));
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        txt_alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_alamatKeyReleased(evt);
            }
        });
        jPanel1.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 328, 246, 30));

        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 146, 210)));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_usernameKeyReleased(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 246, 30));

        txt_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 146, 210)));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emailKeyReleased(evt);
            }
        });
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 217, 246, 30));

        txt_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 146, 210)));
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passwordKeyReleased(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 254, 246, 30));

        txt_nama_toko.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 146, 210)));
        txt_nama_toko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_tokoActionPerformed(evt);
            }
        });
        txt_nama_toko.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nama_tokoKeyReleased(evt);
            }
        });
        jPanel1.add(txt_nama_toko, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 291, 246, 30));

        btn_selanjutnya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_selanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_selanjutnya.png"))); // NOI18N
        btn_selanjutnya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_selanjutnya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_selanjutnyaMouseClicked(evt);
            }
        });
        jPanel1.add(btn_selanjutnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel7.setText("V 1.5");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 40, 20));

        lbl_emailconfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_emailconfirmKeyReleased(evt);
            }
        });
        jPanel1.add(lbl_emailconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 224, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_nama_tokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_tokoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_tokoActionPerformed

    private void btn_selanjutnyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_selanjutnyaMouseClicked
        //insert into akun
         if(!txt_email.getText().contains("@")){
            lbl_emailconfirm.setText("Masukkan email dengan benar");
        }else{
            lbl_emailconfirm.setText("");
       try{
           String sql="INSERT INTO akun (`nama_toko`, `nama_pemilik`, `alamat`, `username`, `email`, `password`) VALUES ('"
                    +txt_nama_toko.getText()+"','"
                    +txt_nama_pemilik.getText()+"','"
                    +txt_alamat.getText()+"','"
                    +txt_username.getText()+"','"
                    +txt_email.getText()+"','"
                    +txt_password.getText()+"')";
            java.sql.Connection conn= (Connection) koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil membuat akun.\nSilahkan login kembali");
            this.setVisible(false);
            new Login().setVisible(true);
        }catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
                }
    }//GEN-LAST:event_btn_selanjutnyaMouseClicked

    private void txt_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyReleased
        // TODO add your handling code here:
       txt_username.setText(txt_username.getText().toUpperCase());
    }//GEN-LAST:event_txt_usernameKeyReleased

    private void txt_nama_pemilikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nama_pemilikKeyReleased
        // TODO add your handling code here:
        txt_nama_pemilik.setText(txt_nama_pemilik.getText().toUpperCase());
    }//GEN-LAST:event_txt_nama_pemilikKeyReleased

    private void txt_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyReleased
        // TODO add your handling code here:
        if(!txt_email.getText().contains("@")){
            btn_selanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selanjutnya off.png")));
            btn_selanjutnya.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            lbl_emailconfirm.setText("Masukkan email dengan benar");
        }else{
            btn_selanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_selanjutnya.png")));
            btn_selanjutnya.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            lbl_emailconfirm.setText("");
        }
    }//GEN-LAST:event_txt_emailKeyReleased

    private void txt_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyReleased
        // TODO add your handling code here:
        txt_password.setText(txt_password.getText().toUpperCase());
    }//GEN-LAST:event_txt_passwordKeyReleased

    private void txt_nama_tokoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nama_tokoKeyReleased
        // TODO add your handling code here:
        txt_nama_toko.setText(txt_nama_toko.getText().toUpperCase());
    }//GEN-LAST:event_txt_nama_tokoKeyReleased

    private void txt_alamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_alamatKeyReleased
        // TODO add your handling code here:
        txt_alamat.setText(txt_alamat.getText().toUpperCase());
    }//GEN-LAST:event_txt_alamatKeyReleased

    private void lbl_emailconfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_emailconfirmKeyReleased
        // TODO add your handling code here:
        /*if(!txt_email.getText().contains("@")){
            btn_selanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dashboard/btn simpan disabled.png")));
            btn_selanjutnya.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            btn_selanjutnya.setText("Masukkan email dengan benar");
        }else{
            btn_selanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_selanjutnya.png")));
            btn_selanjutnya.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            btn_selanjutnya.setText("");
        }*/
    }//GEN-LAST:event_lbl_emailconfirmKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_selanjutnya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_emailconfirm;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nama_pemilik;
    private javax.swing.JTextField txt_nama_toko;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
