package toko.kelontong;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eichenar
 */
public class Tentang extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    
    
    
    
    public Tentang() {
        initComponents();
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submenu = new javax.swing.JPanel();
        bt_dev = new javax.swing.JLabel();
        bt_desc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        desc = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dev = new javax.swing.JPanel();
        bt_logout4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submenu.setBackground(new java.awt.Color(255, 255, 255));
        submenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_dev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tentang/btn dev off.png"))); // NOI18N
        bt_dev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_dev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_devMouseClicked(evt);
            }
        });
        submenu.add(bt_dev, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        bt_desc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tentang/btn desc on.png"))); // NOI18N
        bt_desc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_descMouseClicked(evt);
            }
        });
        submenu.add(bt_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tentang/bg submenu.png"))); // NOI18N
        submenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        add(submenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 200, 440));

        desc.setBackground(new java.awt.Color(255, 255, 255));
        desc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Release year\t: 2022");
        desc.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 310, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(66, 133, 244));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Description");
        desc.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Version\t : 1.2 (Beta) ");
        desc.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 230, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Develop by \t: Cek Toko Kelontong");
        desc.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 320, -1));

        add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 680, 450));

        dev.setBackground(new java.awt.Color(255, 255, 255));
        dev.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_logout4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tentang/Developer Member.png"))); // NOI18N
        bt_logout4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dev.add(bt_logout4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        add(dev, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 680, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void bt_devMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_devMouseClicked
        // TODO add your handling code here:
        bt_desc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tentang/btn desc off.png")));
        bt_dev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tentang/btn dev on.png")));
        dev.setVisible(true);
        desc.setVisible(false);
        
    }//GEN-LAST:event_bt_devMouseClicked

    private void bt_descMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_descMouseClicked
        // TODO add your handling code here:
        bt_desc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tentang/btn desc on.png")));
        bt_dev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tentang/btn dev off.png")));
        dev.setVisible(false);
        desc.setVisible(true);
    }//GEN-LAST:event_bt_descMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_desc;
    private javax.swing.JLabel bt_dev;
    private javax.swing.JLabel bt_logout4;
    private javax.swing.JPanel desc;
    private javax.swing.JPanel dev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel submenu;
    // End of variables declaration//GEN-END:variables
}
