/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toko.kelontong;

import java.sql.Connection;
import kasir.kasirAPP;

/**
 *
 * @author SYNSGATS
 */
public class TRANSAKSI extends javax.swing.JFrame {
    /*public void logout(){
        this.dispose();
        new Login().setVisible(true);
    }

    /**
     * Creates new form TRANSAKSI
     */
    Dashboard db = new Dashboard();
    
    public TRANSAKSI() {
        initComponents();
        pemilik();
        Dashboard dashboard;
        dashboard = new Dashboard();
        pnldashboard.add(dashboard);
        dashboard.setVisible(true);
        pnldashboard.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainlyot = new javax.swing.JPanel();
        lbldsbrd = new javax.swing.JLabel();
        lblstok = new javax.swing.JLabel();
        lblhtg = new javax.swing.JLabel();
        lbl_ttg = new javax.swing.JLabel();
        lbltrnsk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bt_logout = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnldashboard = new javax.swing.JPanel();
        pnlstok = new javax.swing.JPanel();
        pnlhtng = new javax.swing.JPanel();
        pnltrnski = new javax.swing.JPanel();
        pnlttg = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PEMBUKUAN");
        setPreferredSize(new java.awt.Dimension(890, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainlyot.setBackground(new java.awt.Color(255, 255, 255));
        mainlyot.setMaximumSize(new java.awt.Dimension(800, 500));
        mainlyot.setPreferredSize(new java.awt.Dimension(400, 500));
        mainlyot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbldsbrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard on.png"))); // NOI18N
        lbldsbrd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbldsbrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldsbrdMouseClicked(evt);
            }
        });
        mainlyot.add(lbldsbrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, -1));

        lblstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok off (1).png"))); // NOI18N
        lblstok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblstok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblstokMouseClicked(evt);
            }
        });
        mainlyot.add(lblstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        lblhtg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hutang off (1).png"))); // NOI18N
        lblhtg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhtg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhtgMouseClicked(evt);
            }
        });
        mainlyot.add(lblhtg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        lbl_ttg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tentang off (1).png"))); // NOI18N
        lbl_ttg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ttg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ttgMouseClicked(evt);
            }
        });
        mainlyot.add(lbl_ttg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        lbltrnsk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi off (1).png"))); // NOI18N
        lbltrnsk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbltrnsk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbltrnskMouseClicked(evt);
            }
        });
        mainlyot.add(lbltrnsk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\TOKO KELONTONG\\src\\img\\bg menu.png")); // NOI18N
        mainlyot.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bt_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\TOKO KELONTONG\\src\\img\\logout text.png")); // NOI18N
        bt_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_logoutMouseClicked(evt);
            }
        });
        mainlyot.add(bt_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 80, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\TOKO KELONTONG\\src\\img\\kasir with text.png")); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        mainlyot.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 110, 50));

        getContentPane().add(mainlyot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 50));

        pnldashboard.setBackground(new java.awt.Color(255, 255, 255));
        pnldashboard.setPreferredSize(new java.awt.Dimension(880, 448));
        pnldashboard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnldashboardKeyPressed(evt);
            }
        });
        pnldashboard.setLayout(new javax.swing.BoxLayout(pnldashboard, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pnldashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 440));

        pnlstok.setBackground(new java.awt.Color(255, 255, 255));
        pnlstok.setPreferredSize(new java.awt.Dimension(880, 448));
        pnlstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnlstokKeyPressed(evt);
            }
        });
        pnlstok.setLayout(new javax.swing.BoxLayout(pnlstok, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pnlstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 440));

        pnlhtng.setBackground(new java.awt.Color(255, 255, 255));
        pnlhtng.setPreferredSize(new java.awt.Dimension(880, 448));
        pnlhtng.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnlhtngKeyPressed(evt);
            }
        });
        pnlhtng.setLayout(new javax.swing.BoxLayout(pnlhtng, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pnlhtng, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 440));

        pnltrnski.setBackground(new java.awt.Color(255, 255, 255));
        pnltrnski.setPreferredSize(new java.awt.Dimension(880, 448));
        pnltrnski.setLayout(new javax.swing.BoxLayout(pnltrnski, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pnltrnski, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 440));

        pnlttg.setBackground(new java.awt.Color(255, 255, 255));
        pnlttg.setPreferredSize(new java.awt.Dimension(880, 448));
        pnlttg.setLayout(new javax.swing.BoxLayout(pnlttg, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(pnlttg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 440));

        setSize(new java.awt.Dimension(906, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    public void callpemilik(){
//        pemilik();
//    }
    
    
    public void pemilik(){
        try{
            String sql = "SELECT nama_toko FROM akun;";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            res.next();
            //lbl_pemilik.setText(res.getString(1));
            
        }
        catch (Exception e){           
        }
    }
    
    private void lbldsbrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldsbrdMouseClicked
        // TODO add your handling code here:
        Dashboard dashboard;
        dashboard = new Dashboard();
        pnldashboard.add(dashboard);
        dashboard.setVisible(true);
        pnldashboard.setVisible(true);
        pnlstok.setVisible(false);
        pnlhtng.setVisible(false);
        pnltrnski.setVisible(false);
        pnlttg.setVisible(false);
        
        lbltrnsk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi off (1).png")));
        lbl_ttg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tentang off (1).png"))); 
        lblhtg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hutang off (1).png")));
        lblstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok off (1).png")));
        lbldsbrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard on.png")));
    }//GEN-LAST:event_lbldsbrdMouseClicked

    private void lblstokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblstokMouseClicked
        // TODO add your handling code here:
        Panel_Stok stok;
        stok = new Panel_Stok();
        pnlstok.add(stok);
        stok.setVisible(true);
        pnlstok.setVisible(true);
        pnltrnski.setVisible(false);
        pnlhtng.setVisible(false);
        pnldashboard.setVisible(false);
        pnlttg.setVisible(false);
        
        
        lbltrnsk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi off (1).png")));
        lbl_ttg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tentang off (1).png"))); 
        lblhtg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hutang off (1).png")));
        lblstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok on.png")));
        lbldsbrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard off (1).png")));
    }//GEN-LAST:event_lblstokMouseClicked

    private void lblhtgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhtgMouseClicked
        // TODO add your handling code here:
        pn_hutang htg;
        htg = new pn_hutang();
        pnlhtng.add(htg);
        htg.setVisible(true);
        pnlhtng.setVisible(true);
        pnlstok.setVisible(false);
        pnltrnski.setVisible(false);
        pnldashboard.setVisible(false);
        pnlttg.setVisible(false);
        
        lbltrnsk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi off (1).png")));
        lbl_ttg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tentang off (1).png"))); 
        lblhtg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hutang on.png")));
        lblstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok off (1).png")));
        lbldsbrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard off (1).png")));
    }//GEN-LAST:event_lblhtgMouseClicked

    private void lbltrnskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltrnskMouseClicked
        // TODO add your handling code here:
        TRANSAKSI2 transaksi;
        transaksi = new TRANSAKSI2();
        pnltrnski.add(transaksi);
        transaksi.setVisible(true);
        pnltrnski.setVisible(true);
        pnlstok.setVisible(false);
        pnlhtng.setVisible(false);
        pnldashboard.setVisible(false);
        pnlttg.setVisible(false);
        
        lbltrnsk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi on.png")));
        lbl_ttg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tentang off (1).png"))); 
        lblhtg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hutang off (1).png")));
        lblstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok off (1).png")));
        lbldsbrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard off (1).png")));
    }//GEN-LAST:event_lbltrnskMouseClicked

    private void lbl_ttgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ttgMouseClicked
        // TODO add your handling code here:
        Tentang ttg;
        ttg = new Tentang();
        pnlttg.add(ttg);
        ttg.setVisible(true); 
        pnlttg.setVisible(true);
        pnlstok.setVisible(false);
        pnlhtng.setVisible(false);
        pnldashboard.setVisible(false);
        pnltrnski.setVisible(false);
        
        lbltrnsk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/transaksi off (1).png")));
        lbl_ttg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tentang on.png")));
        lblhtg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hutang off (1).png")));
        lblstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stok off (1).png")));
        lbldsbrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard off (1).png")));
    }//GEN-LAST:event_lbl_ttgMouseClicked

    private void pnlstokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnlstokKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlstokKeyPressed

    private void pnlhtngKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnlhtngKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlhtngKeyPressed

    private void pnldashboardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnldashboardKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnldashboardKeyPressed

    private void bt_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_logoutMouseClicked
        // TODO add your handling code here:
        dispose();
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_bt_logoutMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        dispose();
        kasir.kasirAPP log = new kasirAPP();
        log.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TRANSAKSI().setVisible(true);
                new Login().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_ttg;
    private javax.swing.JLabel lbldsbrd;
    private javax.swing.JLabel lblhtg;
    private javax.swing.JLabel lblstok;
    private javax.swing.JLabel lbltrnsk;
    private javax.swing.JPanel mainlyot;
    private javax.swing.JPanel pnldashboard;
    private javax.swing.JPanel pnlhtng;
    private javax.swing.JPanel pnlstok;
    private javax.swing.JPanel pnltrnski;
    private javax.swing.JPanel pnlttg;
    // End of variables declaration//GEN-END:variables
}
